kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '8'
  name: laravel-vue
  #namespace: ahmed
  labels:
    layer: laravel
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      layer: laravel
      tier: backend
  template:
    metadata:
      labels:
        layer: laravel
        tier: backend
    spec:
      securityContext:
        fsGroup: 33
      volumes:
        # Laravel Source Code Volume
        - name: laravel-volume
          persistentVolumeClaim:
            claimName: laravel-pvc
      containers:
        # Laravel Containers
        - name: laravel
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: laravel-volume
              mountPath: /var/www/storage
              subPath: storage
            - name: laravel-volume
              mountPath: /var/www/storage/app
              subPath: app
            - name: laravel-volume
              mountPath: /var/www/storage/framework/cache
              subPath: cache
            - name: laravel-volume
              mountPath: /var/www/storage/framework/cache/data
              subPath: data
            - name: laravel-volume
              mountPath: /var/www/storage/framework/sessions
              subPath: sessions
            - name: laravel-volume
              mountPath: /var/www/storage/framework/testing
              subPath: testing
            - name: laravel-volume
              mountPath: /var/www/storage/framework/views
              subPath: views
            - name: laravel-volume
              mountPath: /var/www/storage/logs
              subPath: logs
          image: 'docker.io/ahmademje/php-oci8'
      initContainers:
        - name: initcontainer # Or replace the name
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
          - chown 33:33 storage; # Replace UID and GID with values from the Dockerfile
          volumeMounts:
          - name: laravel-volume  # Or you can replace with any name
            mountPath: /storage # Must match the mount path in the args line
      imagePullSecrets:
        - name: ahmad-pull-secret
